
[features]
seeds = true
skip-lint = false

[programs.devnet]
slik = "CogFZCvMEXKpvg2okzEUQMLAeTRqwdC9v7JXE8CHvzNP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
