[package]
name = "slik"
version = "0.1.0"
description = "SLIK - 6-code payments on Solana (inspired by BLIK)"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "slik"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = "=0.29.0"
anchor-spl = "=0.29.0"
solana-program = "=1.18.26"
[patch.crates-io]
toml_datetime = { path = "./toml/crates/toml_datetime" }
toml_parser = { path = "./toml/crates/toml_parser" }
